### PR TITLE
add sum method

### LINKED ISSUE #26: Add Sum method
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum?view=netcore-2.1

### PR DESCRIPTION
**Pull request by rugglcon**
closes #26

### CODE REVIEW

**Comment by jreina** [comment]
Please add bindings in index.js, tests, and type definitions.

**Comment by jreina** [comment]
In order to close #26, we should also implement an overload of `Sum<T>(((x: T) => number)): number`. I don't mind merging as-is (gives more opportunities for others to contribute), but we would need to keep #26 open. Do you want this merged as-is?

**Comment by rugglcon** [comment]
Yeah I think it's okay to merge as is, you're right about allowing others to contribute. I could update the issue if you want or you could about the other implementation, just let me know.

**Comment by jreina** [comment]
Thank you for your contribution. Happy hacking 🎃

**Pull request merged**
