### PR TITLE
add Count method

### LINKED ISSUE #7: Add Count method
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.count?view=netcore-2.1

### PR DESCRIPTION
**Pull request by rugglcon**
reference: #7

### CODE REVIEW

**Comment by jreina** [comment]
Please add bindings in index.js, tests, and type definitions.

**Comment by jreina** [comment]
In order to close #7 we need to implement an overload `Count<T>: ((x: T) => boolean): number`. Do you want to merge as-is and keep the issue open?

**Comment by rugglcon** [comment]
Same as I said on my other PR, I think it's okay as is and we can allow others to contribute as well.

**Comment by jreina** [comment]
Thank you for your contribution. Happy hacking 🎃

**Pull request merged**
